/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // But you can create a sidebar manually
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      href: 'https://github.com/bigcapitalhq/bigcapital/releases',
      label: 'Releases',
    },
    {
      type: 'link',
      href: 'https://github.com/bigcapitalhq/bigcapital/blob/develop/CONTRIBUTING.md',
      label: 'Contribute',
    },
  ],
};

module.exports = sidebars;
